%%

% Define the path for the first-level stats results.
stats_path = '/mnt/lustre/users/psych/ns605/Analysis/SPM/First_level/'

% CONTRAST 1 - GO OVER SUCCESSFUL STOP

% Factorial design specification

matlabbatch{1}.spm.stats.factorial_design.dir = {'/mnt/lustre/users/psych/ns605/Analysis/SPM/Higher_level/Group_Go'};
matlabbatch{1}.spm.stats.factorial_design.des.t1.scans = {
                                                          fullfile(stats_path, 'sub-10159/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10171/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10189/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10206/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10217/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10225/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10227/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10228/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10235/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10249/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10271/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10273/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10274/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10280/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10290/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10292/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10304/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10316/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10321/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10325/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10329/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10339/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10340/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10345/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10347/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10356/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10361/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10365/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10376/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10377/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10388/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10438/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10440/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10448/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10455/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10460/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10471/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10478/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10487/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10492/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10506/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10517/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10523/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10524/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10525/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10530/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10557/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10565/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10570/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10575/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10624/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10629/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10631/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10638/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10668/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10672/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10674/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10678/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10680/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10686/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10692/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10697/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10704/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10707/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10708/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10719/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10724/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10746/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10762/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10779/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10785/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10788/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10844/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10855/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10871/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10877/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10882/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10891/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10893/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10912/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10934/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10940/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10949/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10958/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10963/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10968/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10975/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10977/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10987/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-10998/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-11019/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-11030/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-11044/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-11050/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-11052/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-11059/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-11061/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-11062/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-11066/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-11067/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-11068/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-11077/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-11088/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-11090/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-11098/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-11104/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-11105/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-11106/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-11108/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-11112/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-11122/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-11128/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-11131/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-11142/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-11143/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-11149/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-11156/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50004/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50006/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50007/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50013/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50014/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50015/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50016/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50020/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50021/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50022/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50023/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50025/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50027/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50029/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50032/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50033/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50034/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50035/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50036/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50038/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50043/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50047/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50048/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50049/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50050/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50051/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50052/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50054/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50055/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50056/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50058/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50064/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50066/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50067/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50069/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50073/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50075/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50076/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50077/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50080/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50081/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50083/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-50085/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60001/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60005/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60006/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60008/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60010/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60011/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60012/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60014/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60015/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60016/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60017/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60020/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60021/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60022/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60028/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60030/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60033/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60036/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60037/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60038/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60042/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60043/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60045/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60046/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60048/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60049/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60051/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60052/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60053/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60055/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60056/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60057/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60060/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60062/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60065/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60066/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60068/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60070/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60072/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60073/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60074/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60076/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60077/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60078/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60079/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60080/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60084/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60087/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-60089/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70001/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70004/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70007/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70015/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70017/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70020/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70021/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70022/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70026/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70029/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70033/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70034/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70037/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70040/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70046/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70048/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70049/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70051/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70052/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70055/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70057/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70058/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70060/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70061/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70065/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70068/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70069/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70070/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70072/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70073/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70074/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70075/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70076/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70077/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70079/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70080/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70081/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70083/con_0001.nii,1')
                                                          fullfile(stats_path, 'sub-70086/con_0001.nii,1')
                                                          };
matlabbatch{1}.spm.stats.factorial_design.cov = struct('c', {}, 'cname', {}, 'iCFI', {}, 'iCC', {});
matlabbatch{1}.spm.stats.factorial_design.multi_cov = struct('files', {}, 'iCFI', {}, 'iCC', {});
matlabbatch{1}.spm.stats.factorial_design.masking.tm.tm_none = 1;
matlabbatch{1}.spm.stats.factorial_design.masking.im = 1;
matlabbatch{1}.spm.stats.factorial_design.masking.em = {''};
matlabbatch{1}.spm.stats.factorial_design.globalc.g_omit = 1;
matlabbatch{1}.spm.stats.factorial_design.globalm.gmsca.gmsca_no = 1;
matlabbatch{1}.spm.stats.factorial_design.globalm.glonorm = 1;

% Model estimation

matlabbatch{2}.spm.stats.fmri_est.spmmat = {'/mnt/lustre/users/psych/ns605/Analysis/SPM/Higher_level/Group_Go/SPM.mat'};
matlabbatch{2}.spm.stats.fmri_est.write_residuals = 0;
matlabbatch{2}.spm.stats.fmri_est.method.Classical = 1;

% Contrast Manager

matlabbatch{3}.spm.stats.con.spmmat = {'/mnt/lustre/users/psych/ns605/Analysis/SPM/Higher_level/Group_Go/SPM.mat'};
matlabbatch{3}.spm.stats.con.consess{1}.tcon.name = 'go_stop_success';
matlabbatch{3}.spm.stats.con.consess{1}.tcon.weights = 1;
matlabbatch{3}.spm.stats.con.consess{1}.tcon.sessrep = 'none';
matlabbatch{3}.spm.stats.con.delete = 0;

% Results Report

matlabbatch{4}.spm.stats.results.spmmat = {'/mnt/lustre/users/psych/ns605/Analysis/SPM/Higher_level/Group_Go/SPM.mat'};
matlabbatch{4}.spm.stats.results.conspec.titlestr = '';
matlabbatch{4}.spm.stats.results.conspec.contrasts = 1;
matlabbatch{4}.spm.stats.results.conspec.threshdesc = 'none';
matlabbatch{4}.spm.stats.results.conspec.thresh = 0.05;
matlabbatch{4}.spm.stats.results.conspec.extent = 112;
matlabbatch{4}.spm.stats.results.conspec.conjunction = 1;
matlabbatch{4}.spm.stats.results.conspec.mask.none = 1;
matlabbatch{4}.spm.stats.results.units = 1;
matlabbatch{4}.spm.stats.results.export{1}.ps = true;
matlabbatch{4}.spm.stats.results.export{2}.tspm.basename = 'thr';

% CONTRAST 2 - SUCCESSFUL STOP OVER GO

% Factorial design specification

matlabbatch{5}.spm.stats.factorial_design.dir = {'/mnt/lustre/users/psych/ns605/Analysis/SPM/Higher_level/Group_Stop'};
matlabbatch{5}.spm.stats.factorial_design.des.t1.scans = {
                                                          fullfile(stats_path, 'sub-10159/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10171/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10189/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10206/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10217/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10225/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10227/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10228/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10235/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10249/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10271/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10273/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10274/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10280/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10290/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10292/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10304/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10316/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10321/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10325/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10329/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10339/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10340/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10345/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10347/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10356/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10361/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10365/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10376/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10377/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10388/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10438/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10440/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10448/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10455/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10460/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10471/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10478/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10487/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10492/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10506/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10517/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10523/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10524/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10525/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10530/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10557/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10565/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10570/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10575/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10624/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10629/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10631/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10638/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10668/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10672/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10674/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10678/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10680/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10686/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10692/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10697/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10704/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10707/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10708/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10719/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10724/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10746/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10762/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10779/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10785/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10788/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10844/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10855/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10871/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10877/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10882/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10891/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10893/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10912/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10934/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10940/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10949/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10958/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10963/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10968/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10975/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10977/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10987/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-10998/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-11019/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-11030/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-11044/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-11050/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-11052/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-11059/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-11061/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-11062/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-11066/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-11067/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-11068/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-11077/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-11088/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-11090/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-11098/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-11104/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-11105/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-11106/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-11108/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-11112/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-11122/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-11128/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-11131/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-11142/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-11143/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-11149/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-11156/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50004/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50006/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50007/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50013/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50014/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50015/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50016/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50020/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50021/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50022/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50023/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50025/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50027/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50029/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50032/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50033/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50034/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50035/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50036/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50038/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50043/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50047/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50048/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50049/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50050/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50051/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50052/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50054/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50055/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50056/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50058/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50064/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50066/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50067/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50069/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50073/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50075/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50076/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50077/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50080/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50081/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50083/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-50085/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60001/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60005/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60006/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60008/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60010/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60011/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60012/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60014/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60015/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60016/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60017/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60020/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60021/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60022/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60028/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60030/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60033/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60036/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60037/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60038/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60042/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60043/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60045/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60046/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60048/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60049/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60051/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60052/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60053/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60055/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60056/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60057/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60060/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60062/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60065/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60066/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60068/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60070/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60072/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60073/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60074/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60076/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60077/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60078/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60079/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60080/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60084/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60087/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-60089/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70001/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70004/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70007/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70015/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70017/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70020/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70021/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70022/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70026/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70029/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70033/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70034/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70037/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70040/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70046/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70048/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70049/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70051/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70052/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70055/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70057/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70058/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70060/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70061/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70065/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70068/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70069/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70070/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70072/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70073/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70074/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70075/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70076/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70077/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70079/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70080/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70081/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70083/con_0002.nii,1')
                                                          fullfile(stats_path, 'sub-70086/con_0002.nii,1')
                                                          };
matlabbatch{5}.spm.stats.factorial_design.cov = struct('c', {}, 'cname', {}, 'iCFI', {}, 'iCC', {});
matlabbatch{5}.spm.stats.factorial_design.multi_cov = struct('files', {}, 'iCFI', {}, 'iCC', {});
matlabbatch{5}.spm.stats.factorial_design.masking.tm.tm_none = 1;
matlabbatch{5}.spm.stats.factorial_design.masking.im = 1;
matlabbatch{5}.spm.stats.factorial_design.masking.em = {''};
matlabbatch{5}.spm.stats.factorial_design.globalc.g_omit = 1;
matlabbatch{5}.spm.stats.factorial_design.globalm.gmsca.gmsca_no = 1;
matlabbatch{5}.spm.stats.factorial_design.globalm.glonorm = 1;

% Model estimation

matlabbatch{6}.spm.stats.fmri_est.spmmat = {'/mnt/lustre/users/psych/ns605/Analysis/SPM/Higher_level/Group_Stop/SPM.mat'};
matlabbatch{6}.spm.stats.fmri_est.write_residuals = 0;
matlabbatch{6}.spm.stats.fmri_est.method.Classical = 1;

% Contrast Manager

matlabbatch{7}.spm.stats.con.spmmat = {'/mnt/lustre/users/psych/ns605/Analysis/SPM/Higher_level/Group_Stop/SPM.mat'};
matlabbatch{7}.spm.stats.con.consess{1}.tcon.name = 'stop_success_go';
matlabbatch{7}.spm.stats.con.consess{1}.tcon.weights = 1;
matlabbatch{7}.spm.stats.con.consess{1}.tcon.sessrep = 'none';
matlabbatch{7}.spm.stats.con.delete = 0;

% Results Report

matlabbatch{8}.spm.stats.results.spmmat = {'/mnt/lustre/users/psych/ns605/Analysis/SPM/Higher_level/Group_Stop/SPM.mat'};
matlabbatch{8}.spm.stats.results.conspec.titlestr = '';
matlabbatch{8}.spm.stats.results.conspec.contrasts = 1;
matlabbatch{8}.spm.stats.results.conspec.threshdesc = 'none';
matlabbatch{8}.spm.stats.results.conspec.thresh = 0.05;
matlabbatch{8}.spm.stats.results.conspec.extent = 37226;
matlabbatch{8}.spm.stats.results.conspec.conjunction = 1;
matlabbatch{8}.spm.stats.results.conspec.mask.none = 1;
matlabbatch{8}.spm.stats.results.units = 1;
matlabbatch{8}.spm.stats.results.export{1}.ps = true;
matlabbatch{8}.spm.stats.results.export{2}.tspm.basename = 'thr';
