#!/bin/bash

#Defines the directory containing first-level results, and that intended for Featquery.
stats_dir=<full path redacted>/SPM/First_level
featquery_dir=<full path redacted>/SPM/Featquery

#Find folders containing the string 'sub' in stats_dir
subject_folders=($(find "$stats_dir" -type d -name "*sub*"))

#Iterate over the found folders
for subject_folder in "${subject_folders[@]}"; do

    #Extract the folder name without the path
    subject=$(basename "$subject_folder")

    #Create a folder with the same name within featquery_dir
    featquery_subject_dir="$featquery_dir/$subject"
    mkdir -p "$featquery_subject_dir"
    mkdir -p "$featquery_subject_dir/stats" 

    #In order for Featquery to run on SPM data, we have to place files in the directory which look like they're generated by
    #FSL FEAT. Here, templates for these files in SPM space are copied into each subject's Featquery folder.
    cp "<full path redacted>/SPM/SPM_space_files/example_func.nii.gz" "$featquery_subject_dir/example_func.nii.gz"
    cp "<full path redacted>/SPM/SPM_space_files/mask.nii.gz" "$featquery_subject_dir/mask.nii.gz"

    #Copy statistical images for the first and second contrast into the Featquery folder.
    cp "$subject_folder/spmT_0001.nii" "$featquery_subject_dir/stats/tstat1.nii"
    cp "$subject_folder/spmT_0002.nii" "$featquery_subject_dir/stats/tstat2.nii"

    #Zip the stats images.
    gzip -f "$featquery_subject_dir/stats/tstat1.nii"
    gzip -f "$featquery_subject_dir/stats/tstat2.nii"

done
